name: Run matchup finder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * 0" # Run at 11 AM every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm install

      - name: Install ts-node
        run: npm install -g ts-node

      - name: Run script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AXIOM_DATASET: ${{ secrets.AXIOM_DATASET }}
          AXIOM_ORG_ID: ${{ secrets.AXIOM_ORG_ID }}
          AXIOM_AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: ts-node actionsTest.ts
