name: Run matchup builder

on:
  workflow_dispatch:
    inputs:
      ODDS_DAY_OFFSET:
        description: "Days in the future to fetch odds. Today is 0 and defualts to 1"
        required: false
        type: string
  # schedule:
  #   - cron: "0 1-14/4 * * *" # Every 4 hours between 1am and 2pm UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm ci

      - name: Install ts-node
        run: npm install -g ts-node

      - name: Run script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AXIOM_DATASET: ${{ secrets.AXIOM_DATASET }}
          AXIOM_ORG_ID: ${{ secrets.AXIOM_ORG_ID }}
          AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          LINES_BASE_URL: ${{ secrets.LINES_BASE_URL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          ODDS_DAY_OFFSET: ${{ inputs.ODDS_DAY_OFFSET}}
        run: ts-node matchupBuilder.ts
