name: Run matchup finder

on:
  workflow_dispatch:
    inputs:
      START_DATE:
        description: "Initial date in format YYYY-MM-DD that the DAY_OFFSET will reference"
        required: false
        type: string
      DAY_OFFSET:
        description: "Number of days after START_DATE to start looking for matchups"
        required: false
        type: number
  schedule:
    - cron: "0 11 * * 0" # Run at 11 AM every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm ci

      - name: Install ts-node
        run: npm install -g ts-node

      - name: Run script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AXIOM_DATASET: ${{ secrets.AXIOM_DATASET }}
          AXIOM_ORG_ID: ${{ secrets.AXIOM_ORG_ID }}
          AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          START_DATE: ${{ inputs.START_DATE }}
          DAY_OFFSET: ${{ inputs.DAY_OFFSET }}
        run: ts-node matchupFinder.ts
